### ISSUE TITLE
Bookmarks/Presets

### ISSUE THREAD

**Issue by scott-lucius-space** [tractr/directus-sync#31]
Any thoughts on adding bookmarks/presets as a synced collection? I realize this may be better as a manually enabled collection rather than a default one since the collection can grow quickly but with the help of the onQuery hook filter, I'm hoping to pull out all globally set presets that get applied to a fresh Directus instance and keep them with the schema syncing.

**Comment by EdouardDem** [comment]
@scott-lucius-space At first, I didn't consider this option because directus-sync doesn't synchronize users. It therefore seemed impossible to sync presets and bookmarks whose users are not.
If you consider synchronizing global presets and bookmarks, then it becomes possible.
I'm going to need this feature for a project in the next few days. I'll look into it.
There are 2 options that come to mind:
- Synchronize only presets & bookmarks that are global (i.e. have no user)
- Synchronize the presets & bookmarks of the current user (the one used for the `pull` command) and make these presets & bookmarks global on push.

I think the second solution is the best, as it's not easy with Directus to make a preset or bookmark global.

Translated with DeepL.com (free version)

**Comment by badrange** [comment]
Global preset syncing would be useful for us. (We're not using this project yet, just wanted to give my two cents)

**Comment by scott-lucius-space** [comment]
@EdouardDem I may be misunderstanding but is changing presets from a user to a global not as easy as going into the settings module, choosing the presets collection, selecting from the dropdown in the GUI and saving? Would think it would be just as easy from the API/SDK side as well.

![image](https://github.com/tractr/directus-sync/assets/148500388/2b4727b5-9643-4062-9f4e-e3b0ec415cb3)

Either one of those would without a doubt be super helpful, but I would think doing globals all the way through would make more sense from a consistency side of things?

**Comment by EdouardDem** [comment]
@scott-lucius-space You're right. It's not really difficult. My bad.

The thing is there is not this "scope" dropdown when you bulk edit presets, but leaving the "user" field empty will make the presets "global".

As you suggest, I published a new version that allow presets syncing (#32). Global and role based presets are synced. However, the users' presets are not synced.
