### ISSUE TITLE
Using this extension with directus docker

### ISSUE THREAD

**Issue by laportem** [tractr/directus-sync#63]
Both my dev and prod are run using docker-compose
I am using directus version 10.10.7 on both and the underlying DB is Postgres. This extension is not yet in the Directus Marketplace.
The question is, how do I get this extension to install and work with Directus running using docker.
Thank you

**Comment by EdouardDem** [comment]
Hi @laportem
Currently `directus-extension-sync` is not available in the marketplace but it is [in the roadmap](https://github.com/orgs/tractr/projects/2?pane=issue&itemId=61004602).
Meanwhile, you can add the custom extensions in you Docker container manually.

Create a file `extensions/package.json` and declare the extensions you need. In my projects, I have the following file: 

```json
{
  "name": "directus-extensions",
  "dependencies": {
    "directus-extension-computed-interface": "^1.9.0",
    "directus-extension-editorjs": "^1.5.0",
    "directus-extension-field-actions": "^1.8.4",
    "directus-extension-masked-interface": "^1.1.0",
    "directus-extension-models": "^2.5.2",
    "directus-extension-sync": "^1.1.3"
  }
}
```

Create a `Dockerfile` file to extend the Directus Docker image:

```Dockerfile
FROM node:20-alpine as third-party-ext
RUN apk add python3 g++ make
WORKDIR /extensions
ADD extensions .
RUN npm install
# Move all extensions the starts with directus-extension-, using find, to the /extensions/directus folder
RUN mkdir -p ./directus
RUN cd node_modules && find . -maxdepth 1 -type d -name "directus-extension-*" -exec mv {} ../directus \;

FROM directus/directus:10.10.7
# Copy third party extensions
COPY --from=third-party-ext /extensions/directus ./extensions
```

Finally, in your docker-compose.yml use this custom image:

```yml
  directus:
    build:
      context: .
      dockerfile: Dockerfile
```

There is other ways to achieve this, as discussed [here](https://github.com/directus/directus/discussions/16989).

You may need to flush the `directus-extensions` table and restart Directus in order to force it to detect new extensions.

**Comment by EdouardDem** [comment]
@laportem I have update the installations options in the readme file: https://www.npmjs.com/package/directus-extension-sync#Installation

**Comment by siddhesh021** [comment]
Using this approach, what will be the affect on mount ? means in docker-compose.yaml file we have code like

    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions

So will the extension loads from docker image or from directus?
